/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gallerai API
 * API for Gallerai system
 * OpenAPI spec version: v1
 */
import type {
  GalleraiApplicationFeaturesAuthAcquireTokenRequest,
  GalleraiApplicationFeaturesImagesGetImagePresignedURLRequest,
  GalleraiApplicationFeaturesImagesImagesUploadedRequest,
  GalleraiSharedKernelModelsResultOfExternalAuthProperties,
  GalleraiSharedKernelModelsResultOfLoginResponse,
  GalleraiSharedKernelModelsResultOfResponse,
  GalleraiSharedKernelModelsResultOfResponse2,
  GalleraiSharedKernelModelsResultOfResponse3,
  GalleraiWebAPIFeaturesHelloHelloResponse
} from '../schemas';

import { workerFetch } from '../../lib/worker-client';

export type imagePresignedUrlResponse200 = {
  data: GalleraiSharedKernelModelsResultOfResponse
  status: 200
}

export type imagePresignedUrlResponse401 = {
  data: void
  status: 401
}
    
export type imagePresignedUrlResponseSuccess = (imagePresignedUrlResponse200) & {
  headers: Headers;
};
export type imagePresignedUrlResponseError = (imagePresignedUrlResponse401) & {
  headers: Headers;
};

export type imagePresignedUrlResponse = (imagePresignedUrlResponseSuccess | imagePresignedUrlResponseError)

export const getImagePresignedUrlUrl = () => {


  

  return `/api/images/presigned-url`
}

export const imagePresignedUrl = async (galleraiApplicationFeaturesImagesGetImagePresignedURLRequest: GalleraiApplicationFeaturesImagesGetImagePresignedURLRequest, options?: RequestInit): Promise<imagePresignedUrlResponse> => {
  
  return workerFetch<imagePresignedUrlResponse>(getImagePresignedUrlUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      galleraiApplicationFeaturesImagesGetImagePresignedURLRequest,)
  }
);}



export type imagesUploadedEndpointResponse200 = {
  data: GalleraiSharedKernelModelsResultOfResponse2
  status: 200
}
    
export type imagesUploadedEndpointResponseSuccess = (imagesUploadedEndpointResponse200) & {
  headers: Headers;
};
;

export type imagesUploadedEndpointResponse = (imagesUploadedEndpointResponseSuccess)

export const getImagesUploadedEndpointUrl = () => {


  

  return `/api/images/uploaded`
}

export const imagesUploadedEndpoint = async (galleraiApplicationFeaturesImagesImagesUploadedRequest: GalleraiApplicationFeaturesImagesImagesUploadedRequest, options?: RequestInit): Promise<imagesUploadedEndpointResponse> => {
  
  return workerFetch<imagesUploadedEndpointResponse>(getImagesUploadedEndpointUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      galleraiApplicationFeaturesImagesImagesUploadedRequest,)
  }
);}



/**
 * @summary Simple hello-world test endpoint
 */
export type helloEndpointResponse200 = {
  data: GalleraiWebAPIFeaturesHelloHelloResponse
  status: 200
}
    
export type helloEndpointResponseSuccess = (helloEndpointResponse200) & {
  headers: Headers;
};
;

export type helloEndpointResponse = (helloEndpointResponseSuccess)

export const getHelloEndpointUrl = () => {


  

  return `/api/hello`
}

export const helloEndpoint = async ( options?: RequestInit): Promise<helloEndpointResponse> => {
  
  return workerFetch<helloEndpointResponse>(getHelloEndpointUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type googleLoginEndpointResponse200 = {
  data: GalleraiSharedKernelModelsResultOfExternalAuthProperties
  status: 200
}
    
export type googleLoginEndpointResponseSuccess = (googleLoginEndpointResponse200) & {
  headers: Headers;
};
;

export type googleLoginEndpointResponse = (googleLoginEndpointResponseSuccess)

export const getGoogleLoginEndpointUrl = () => {


  

  return `/api/auth/google`
}

export const googleLoginEndpoint = async ( options?: RequestInit): Promise<googleLoginEndpointResponse> => {
  
  return workerFetch<googleLoginEndpointResponse>(getGoogleLoginEndpointUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type googleCallbackEndpointResponse200 = {
  data: GalleraiSharedKernelModelsResultOfLoginResponse
  status: 200
}
    
export type googleCallbackEndpointResponseSuccess = (googleCallbackEndpointResponse200) & {
  headers: Headers;
};
;

export type googleCallbackEndpointResponse = (googleCallbackEndpointResponseSuccess)

export const getGoogleCallbackEndpointUrl = () => {


  

  return `/api/auth/google/callback`
}

export const googleCallbackEndpoint = async ( options?: RequestInit): Promise<googleCallbackEndpointResponse> => {
  
  return workerFetch<googleCallbackEndpointResponse>(getGoogleCallbackEndpointUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type acquireTokenEndpointResponse200 = {
  data: GalleraiSharedKernelModelsResultOfResponse3
  status: 200
}
    
export type acquireTokenEndpointResponseSuccess = (acquireTokenEndpointResponse200) & {
  headers: Headers;
};
;

export type acquireTokenEndpointResponse = (acquireTokenEndpointResponseSuccess)

export const getAcquireTokenEndpointUrl = () => {


  

  return `/api/auth/acquire-token`
}

export const acquireTokenEndpoint = async (galleraiApplicationFeaturesAuthAcquireTokenRequest: GalleraiApplicationFeaturesAuthAcquireTokenRequest, options?: RequestInit): Promise<acquireTokenEndpointResponse> => {
  
  return workerFetch<acquireTokenEndpointResponse>(getAcquireTokenEndpointUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      galleraiApplicationFeaturesAuthAcquireTokenRequest,)
  }
);}



