/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gallerai API
 * API for Gallerai system
 * OpenAPI spec version: v1
 */
import {
  useQuery,
  type DataTag,
  type DefinedInitialDataOptions,
  type DefinedUseQueryResult,
  type QueryClient,
  type QueryFunction,
  type QueryKey,
  type UndefinedInitialDataOptions,
  type UseQueryOptions,
  type UseQueryResult,
} from '@tanstack/react-query'

import { axiosInstance, type ErrorType } from '../lib/api-client'
import type { GalleraiWebAPIEndpointsHelloHelloResponse } from './schemas'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Simple hello-world test endpoint
 */
export const galleraiWebAPIEndpointsHelloHelloEndpoint = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<GalleraiWebAPIEndpointsHelloHelloResponse>(
    { url: `/api/hello`, method: 'GET', signal },
    options,
  )
}

export const getGalleraiWebAPIEndpointsHelloHelloEndpointQueryKey = () => {
  return [`/api/hello`] as const
}

export const getGalleraiWebAPIEndpointsHelloHelloEndpointQueryOptions = <
  TData = Awaited<ReturnType<typeof galleraiWebAPIEndpointsHelloHelloEndpoint>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof galleraiWebAPIEndpointsHelloHelloEndpoint>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof axiosInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGalleraiWebAPIEndpointsHelloHelloEndpointQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof galleraiWebAPIEndpointsHelloHelloEndpoint>>
  > = ({ signal }) => galleraiWebAPIEndpointsHelloHelloEndpoint(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof galleraiWebAPIEndpointsHelloHelloEndpoint>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GalleraiWebAPIEndpointsHelloHelloEndpointQueryResult = NonNullable<
  Awaited<ReturnType<typeof galleraiWebAPIEndpointsHelloHelloEndpoint>>
>
export type GalleraiWebAPIEndpointsHelloHelloEndpointQueryError = ErrorType<unknown>

export function useGalleraiWebAPIEndpointsHelloHelloEndpoint<
  TData = Awaited<ReturnType<typeof galleraiWebAPIEndpointsHelloHelloEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof galleraiWebAPIEndpointsHelloHelloEndpoint>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof galleraiWebAPIEndpointsHelloHelloEndpoint>>,
          TError,
          Awaited<ReturnType<typeof galleraiWebAPIEndpointsHelloHelloEndpoint>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGalleraiWebAPIEndpointsHelloHelloEndpoint<
  TData = Awaited<ReturnType<typeof galleraiWebAPIEndpointsHelloHelloEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof galleraiWebAPIEndpointsHelloHelloEndpoint>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof galleraiWebAPIEndpointsHelloHelloEndpoint>>,
          TError,
          Awaited<ReturnType<typeof galleraiWebAPIEndpointsHelloHelloEndpoint>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGalleraiWebAPIEndpointsHelloHelloEndpoint<
  TData = Awaited<ReturnType<typeof galleraiWebAPIEndpointsHelloHelloEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof galleraiWebAPIEndpointsHelloHelloEndpoint>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Simple hello-world test endpoint
 */

export function useGalleraiWebAPIEndpointsHelloHelloEndpoint<
  TData = Awaited<ReturnType<typeof galleraiWebAPIEndpointsHelloHelloEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof galleraiWebAPIEndpointsHelloHelloEndpoint>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGalleraiWebAPIEndpointsHelloHelloEndpointQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}
