/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as _authenticatedRouteImport } from './routes/__authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as _authenticatedDashboardIndexRouteImport } from './routes/__authenticated/dashboard/index'
import { Route as _authenticatedDashboardFolderRouteImport } from './routes/__authenticated/dashboard/folder'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedRoute = _authenticatedRouteImport.update({
  id: '/__authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedDashboardIndexRoute =
  _authenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedDashboardFolderRoute =
  _authenticatedDashboardFolderRouteImport.update({
    id: '/dashboard/folder',
    path: '/dashboard/folder',
    getParentRoute: () => _authenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/folder': typeof _authenticatedDashboardFolderRoute
  '/dashboard/': typeof _authenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/folder': typeof _authenticatedDashboardFolderRoute
  '/dashboard': typeof _authenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__authenticated': typeof _authenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/__authenticated/dashboard/folder': typeof _authenticatedDashboardFolderRoute
  '/__authenticated/dashboard/': typeof _authenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/dashboard/folder'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/auth/callback' | '/dashboard/folder' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/__authenticated'
    | '/login'
    | '/auth/callback'
    | '/__authenticated/dashboard/folder'
    | '/__authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _authenticatedRoute: typeof _authenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated': {
      id: '/__authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _authenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated/dashboard/': {
      id: '/__authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof _authenticatedDashboardIndexRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/dashboard/folder': {
      id: '/__authenticated/dashboard/folder'
      path: '/dashboard/folder'
      fullPath: '/dashboard/folder'
      preLoaderRoute: typeof _authenticatedDashboardFolderRouteImport
      parentRoute: typeof _authenticatedRoute
    }
  }
}

interface _authenticatedRouteChildren {
  _authenticatedDashboardFolderRoute: typeof _authenticatedDashboardFolderRoute
  _authenticatedDashboardIndexRoute: typeof _authenticatedDashboardIndexRoute
}

const _authenticatedRouteChildren: _authenticatedRouteChildren = {
  _authenticatedDashboardFolderRoute: _authenticatedDashboardFolderRoute,
  _authenticatedDashboardIndexRoute: _authenticatedDashboardIndexRoute,
}

const _authenticatedRouteWithChildren = _authenticatedRoute._addFileChildren(
  _authenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _authenticatedRoute: _authenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
