networks:
  dev:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ communication port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - dev
  gallerai-db:
    image: postgres:16-alpine
    container_name: gallerai-db
    ports:
    - "5432:5432"
    restart: unless-stopped
    volumes:
    - gallerai_data:/var/lib/postgresql/data
    - ../scripts/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    networks:
    - dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  gallerai.inference-worker:
    profiles: ["worker"]
    container_name: gallerai-inference-worker
    image: ${DOCKER_REGISTRY-}galleraiinferenceworker
    build:
      context: .
      dockerfile: ../gallerai-backend/Gallerai.Workers.InferenceWorker/Dockerfile
    depends_on:
      gallerai-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
    - dev
  gallerai.webapi:
    profiles: ["api"]
    ports:
        - 5100:8080
        - 5101:8081
    container_name: gallerai-api
    image: ${DOCKER_REGISTRY-}galleraiwebapi
    build:
      context: .
      dockerfile: ../gallerai-backend/Gallerai.WebAPI/Dockerfile
    depends_on:
      gallerai-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
    - dev
  gallerai.frontend:
    profiles: ["app"]
    ports:
        - 5173:80
    container_name: gallerai-frontend
    build:
      context: ../gallerai-app
      dockerfile: Dockerfile
    depends_on:
      gallerai.webapi:
        condition: service_started
    restart: always
    networks:
    - dev
volumes:
  rabbitmq_data:
    driver: local  
  gallerai_data:
    driver: local
