services:
  gallerai.inference-worker:
    profiles: ["worker"]
    container_name: gallerai-inference-worker
    image: ${DOCKER_REGISTRY-}galleraiinferenceworker
    build:
      context: .
      dockerfile: ../gallerai-backend/Gallerai.Workers.InferenceWorker/Dockerfile
    networks: [shared-net]
  gallerai.webapi:
    profiles: ["api"]
    ports:
        - 5100:8080
        - 5101:8081
    container_name: gallerai-api
    image: ${DOCKER_REGISTRY-}galleraiwebapi
    build:
      context: .
      dockerfile: ../gallerai-backend/Gallerai.WebAPI/Dockerfile
    networks: [shared-net]
  gallerai.frontend:
    profiles: ["app"]
    ports:
        - 5173:80
    container_name: gallerai-frontend
    build:
      context: ../gallerai-app
      dockerfile: Dockerfile
    depends_on:
      gallerai.webapi:
        condition: service_started
    restart: always
    networks: [shared-net]

networks:
  shared-net:
    external: true
    name: gallerai-net
