/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gallerai API
 * API for Gallerai system
 * OpenAPI spec version: v1
 */

/**
 * the error details object
 */
export interface FastEndpointsProblemDetailsError {
  /** the name of the error or property of the dto that caused the error */
  name?: string;
  /** the reason for the error */
  reason?: string;
  /**
   * the code of the error
   * @nullable
   */
  code?: string | null;
  /**
   * the severity of the error
   * @nullable
   */
  severity?: string | null;
}
