/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gallerai API
 * API for Gallerai system
 * OpenAPI spec version: v1
 */
import type { FastEndpointsProblemDetailsError } from './fastEndpointsProblemDetailsError';

/**
 * RFC7807 compatible problem details/ error response class. this can be used by configuring startup like so:
app.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 */
export interface FastEndpointsProblemDetails {
  type?: string;
  title?: string;
  status?: number;
  instance?: string;
  traceId?: string;
  /**
   * the details of the error
   * @nullable
   */
  detail?: string | null;
  errors?: FastEndpointsProblemDetailsError[];
}
