/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gallerai API
 * API for Gallerai system
 * OpenAPI spec version: v1
 */
import type { GalleraiApplicationFeaturesFoldersGetFolderImagesImageDto } from './galleraiApplicationFeaturesFoldersGetFolderImagesImageDto';

export interface GalleraiApplicationFeaturesFoldersGetFolderImagesResponse {
  images?: GalleraiApplicationFeaturesFoldersGetFolderImagesImageDto[];
}
