/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gallerai API
 * API for Gallerai system
 * OpenAPI spec version: v1
 */

export type GalleraiSharedKernelEnumsImageStatus = typeof GalleraiSharedKernelEnumsImageStatus[keyof typeof GalleraiSharedKernelEnumsImageStatus];


export const GalleraiSharedKernelEnumsImageStatus = {
  PROCESSING: 0,
  UPLOADING: 1,
  ANALYZING: 2,
  READY: 3,
  ANALYSIS_ERROR: 4,
} as const;
