/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gallerai API
 * API for Gallerai system
 * OpenAPI spec version: v1
 */

export interface GalleraiApplicationFeaturesFoldersAddFolderResponse {
  folderId?: string;
  name?: string;
}
