/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gallerai API
 * API for Gallerai system
 * OpenAPI spec version: v1
 */
import type { GalleraiApplicationFeaturesImagesImagesUploadedImageUploadedR2 } from './galleraiApplicationFeaturesImagesImagesUploadedImageUploadedR2';

export interface GalleraiApplicationFeaturesImagesImagesUploadedRequest {
  /** @nullable */
  events?: GalleraiApplicationFeaturesImagesImagesUploadedImageUploadedR2[] | null;
}
