/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gallerai API
 * API for Gallerai system
 * OpenAPI spec version: v1
 */
import type { GalleraiSharedKernelDTOsLoginResponse } from './galleraiSharedKernelDTOsLoginResponse';
import type { GalleraiSharedKernelModelsError } from './galleraiSharedKernelModelsError';

export interface GalleraiSharedKernelModelsResultOfLoginResponse {
  isSuccess?: boolean;
  isFailure?: boolean;
  error?: GalleraiSharedKernelModelsError;
  value?: GalleraiSharedKernelDTOsLoginResponse | null;
}
