/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gallerai API
 * API for Gallerai system
 * OpenAPI spec version: v1
 */
import type { GalleraiApplicationFeaturesAuthAcquireTokenResponse } from './galleraiApplicationFeaturesAuthAcquireTokenResponse';
import type { GalleraiSharedKernelModelsError } from './galleraiSharedKernelModelsError';

export interface GalleraiSharedKernelModelsResultOfResponse3 {
  isSuccess?: boolean;
  isFailure?: boolean;
  error?: GalleraiSharedKernelModelsError;
  value?: GalleraiApplicationFeaturesAuthAcquireTokenResponse | null;
}
