/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gallerai API
 * API for Gallerai system
 * OpenAPI spec version: v1
 */
import type { GalleraiSharedKernelEnumsImageStatus } from './galleraiSharedKernelEnumsImageStatus';

export interface GalleraiApplicationFeaturesFoldersGetFolderImagesImageDto {
  imageId?: string;
  folderId?: string;
  cdnUrl?: string;
  status?: GalleraiSharedKernelEnumsImageStatus;
  /** @nullable */
  aestheticScore?: number | null;
  /** @nullable */
  critique?: string | null;
}
