/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gallerai API
 * API for Gallerai system
 * OpenAPI spec version: v1
 */

export type GalleraiDomainEnumsImageStatus = typeof GalleraiDomainEnumsImageStatus[keyof typeof GalleraiDomainEnumsImageStatus];


export const GalleraiDomainEnumsImageStatus = {
  UPLOADING: 0,
  WAITING_FOR_ANALYSIS: 1,
  ANALYZING: 2,
  READY: 3,
  ERROR: 4,
} as const;
