/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gallerai API
 * API for Gallerai system
 * OpenAPI spec version: v1
 */
import type { GalleraiApplicationFeaturesFoldersAddFolderResponse } from './galleraiApplicationFeaturesFoldersAddFolderResponse';
import type { GalleraiSharedKernelModelsError } from './galleraiSharedKernelModelsError';

export interface GalleraiSharedKernelModelsResultOfResponse4 {
  isSuccess?: boolean;
  isFailure?: boolean;
  error?: GalleraiSharedKernelModelsError;
  value?: GalleraiApplicationFeaturesFoldersAddFolderResponse | null;
}
