/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gallerai API
 * API for Gallerai system
 * OpenAPI spec version: v1
 */
import type { GalleraiDomainEnumsImageStatus } from './galleraiDomainEnumsImageStatus';

export interface GalleraiApplicationFeaturesFoldersGetFolderImagesImageDto {
  imageId?: string;
  folderId?: string;
  cdnUrl?: string;
  status?: GalleraiDomainEnumsImageStatus;
  /** @nullable */
  aestheticScore?: number | null;
}
