/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gallerai API
 * API for Gallerai system
 * OpenAPI spec version: v1
 */

export interface GalleraiApplicationFeaturesImagesGetImagePresignedURLRequest {
  key?: string
  fileName?: string
  contentType?: string
}
