/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Gallerai API
 * API for Gallerai system
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GalleraiApplicationFeaturesAuthAcquireTokenRequest,
  GalleraiApplicationFeaturesImagesGetImagePresignedURLRequest,
  GalleraiApplicationFeaturesImagesImagesUploadedRequest,
  GalleraiSharedKernelModelsResultOfExternalAuthProperties,
  GalleraiSharedKernelModelsResultOfLoginResponse,
  GalleraiSharedKernelModelsResultOfResponse,
  GalleraiSharedKernelModelsResultOfResponse2,
  GalleraiSharedKernelModelsResultOfResponse3,
  GalleraiWebAPIFeaturesHelloHelloResponse
} from '../schemas';

import { customInstance } from '../../lib/api-client-base';
import type { ErrorType } from '../../lib/api-client-base';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const imagePresignedUrl = (
    galleraiApplicationFeaturesImagesGetImagePresignedURLRequest: GalleraiApplicationFeaturesImagesGetImagePresignedURLRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GalleraiSharedKernelModelsResultOfResponse>(
      {url: `/api/images/presigned-url`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: galleraiApplicationFeaturesImagesGetImagePresignedURLRequest, signal
    },
      options);
    }
  


export const getImagePresignedUrlMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof imagePresignedUrl>>, TError,{data: GalleraiApplicationFeaturesImagesGetImagePresignedURLRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof imagePresignedUrl>>, TError,{data: GalleraiApplicationFeaturesImagesGetImagePresignedURLRequest}, TContext> => {

const mutationKey = ['imagePresignedUrl'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof imagePresignedUrl>>, {data: GalleraiApplicationFeaturesImagesGetImagePresignedURLRequest}> = (props) => {
          const {data} = props ?? {};

          return  imagePresignedUrl(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ImagePresignedUrlMutationResult = NonNullable<Awaited<ReturnType<typeof imagePresignedUrl>>>
    export type ImagePresignedUrlMutationBody = GalleraiApplicationFeaturesImagesGetImagePresignedURLRequest
    export type ImagePresignedUrlMutationError = ErrorType<void>

    export const useImagePresignedUrl = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof imagePresignedUrl>>, TError,{data: GalleraiApplicationFeaturesImagesGetImagePresignedURLRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof imagePresignedUrl>>,
        TError,
        {data: GalleraiApplicationFeaturesImagesGetImagePresignedURLRequest},
        TContext
      > => {
      return useMutation(getImagePresignedUrlMutationOptions(options));
    }
    
export const imagesUploadedEndpoint = (
    galleraiApplicationFeaturesImagesImagesUploadedRequest: GalleraiApplicationFeaturesImagesImagesUploadedRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GalleraiSharedKernelModelsResultOfResponse2>(
      {url: `/api/images/uploaded`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: galleraiApplicationFeaturesImagesImagesUploadedRequest, signal
    },
      options);
    }
  


export const getImagesUploadedEndpointMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof imagesUploadedEndpoint>>, TError,{data: GalleraiApplicationFeaturesImagesImagesUploadedRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof imagesUploadedEndpoint>>, TError,{data: GalleraiApplicationFeaturesImagesImagesUploadedRequest}, TContext> => {

const mutationKey = ['imagesUploadedEndpoint'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof imagesUploadedEndpoint>>, {data: GalleraiApplicationFeaturesImagesImagesUploadedRequest}> = (props) => {
          const {data} = props ?? {};

          return  imagesUploadedEndpoint(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ImagesUploadedEndpointMutationResult = NonNullable<Awaited<ReturnType<typeof imagesUploadedEndpoint>>>
    export type ImagesUploadedEndpointMutationBody = GalleraiApplicationFeaturesImagesImagesUploadedRequest
    export type ImagesUploadedEndpointMutationError = ErrorType<unknown>

    export const useImagesUploadedEndpoint = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof imagesUploadedEndpoint>>, TError,{data: GalleraiApplicationFeaturesImagesImagesUploadedRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof imagesUploadedEndpoint>>,
        TError,
        {data: GalleraiApplicationFeaturesImagesImagesUploadedRequest},
        TContext
      > => {
      return useMutation(getImagesUploadedEndpointMutationOptions(options));
    }
    
/**
 * @summary Simple hello-world test endpoint
 */
export const helloEndpoint = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GalleraiWebAPIFeaturesHelloHelloResponse>(
      {url: `/api/hello`, method: 'GET', signal
    },
      options);
    }
  



export const getHelloEndpointQueryKey = () => {
    return [
    `/api/hello`
    ] as const;
    }

    
export const getHelloEndpointQueryOptions = <TData = Awaited<ReturnType<typeof helloEndpoint>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof helloEndpoint>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHelloEndpointQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof helloEndpoint>>> = ({ signal }) => helloEndpoint(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof helloEndpoint>>, TError, TData> & { queryKey: QueryKey }
}

export type HelloEndpointQueryResult = NonNullable<Awaited<ReturnType<typeof helloEndpoint>>>
export type HelloEndpointQueryError = ErrorType<unknown>


/**
 * @summary Simple hello-world test endpoint
 */

export function useHelloEndpoint<TData = Awaited<ReturnType<typeof helloEndpoint>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof helloEndpoint>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHelloEndpointQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const googleLoginEndpoint = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GalleraiSharedKernelModelsResultOfExternalAuthProperties>(
      {url: `/api/auth/google`, method: 'GET', signal
    },
      options);
    }
  



export const getGoogleLoginEndpointQueryKey = () => {
    return [
    `/api/auth/google`
    ] as const;
    }

    
export const getGoogleLoginEndpointQueryOptions = <TData = Awaited<ReturnType<typeof googleLoginEndpoint>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof googleLoginEndpoint>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGoogleLoginEndpointQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof googleLoginEndpoint>>> = ({ signal }) => googleLoginEndpoint(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof googleLoginEndpoint>>, TError, TData> & { queryKey: QueryKey }
}

export type GoogleLoginEndpointQueryResult = NonNullable<Awaited<ReturnType<typeof googleLoginEndpoint>>>
export type GoogleLoginEndpointQueryError = ErrorType<unknown>



export function useGoogleLoginEndpoint<TData = Awaited<ReturnType<typeof googleLoginEndpoint>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof googleLoginEndpoint>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGoogleLoginEndpointQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const googleCallbackEndpoint = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GalleraiSharedKernelModelsResultOfLoginResponse>(
      {url: `/api/auth/google/callback`, method: 'GET', signal
    },
      options);
    }
  



export const getGoogleCallbackEndpointQueryKey = () => {
    return [
    `/api/auth/google/callback`
    ] as const;
    }

    
export const getGoogleCallbackEndpointQueryOptions = <TData = Awaited<ReturnType<typeof googleCallbackEndpoint>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof googleCallbackEndpoint>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGoogleCallbackEndpointQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof googleCallbackEndpoint>>> = ({ signal }) => googleCallbackEndpoint(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof googleCallbackEndpoint>>, TError, TData> & { queryKey: QueryKey }
}

export type GoogleCallbackEndpointQueryResult = NonNullable<Awaited<ReturnType<typeof googleCallbackEndpoint>>>
export type GoogleCallbackEndpointQueryError = ErrorType<unknown>



export function useGoogleCallbackEndpoint<TData = Awaited<ReturnType<typeof googleCallbackEndpoint>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof googleCallbackEndpoint>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGoogleCallbackEndpointQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const acquireTokenEndpoint = (
    galleraiApplicationFeaturesAuthAcquireTokenRequest: GalleraiApplicationFeaturesAuthAcquireTokenRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GalleraiSharedKernelModelsResultOfResponse3>(
      {url: `/api/auth/acquire-token`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: galleraiApplicationFeaturesAuthAcquireTokenRequest, signal
    },
      options);
    }
  


export const getAcquireTokenEndpointMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acquireTokenEndpoint>>, TError,{data: GalleraiApplicationFeaturesAuthAcquireTokenRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof acquireTokenEndpoint>>, TError,{data: GalleraiApplicationFeaturesAuthAcquireTokenRequest}, TContext> => {

const mutationKey = ['acquireTokenEndpoint'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof acquireTokenEndpoint>>, {data: GalleraiApplicationFeaturesAuthAcquireTokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  acquireTokenEndpoint(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AcquireTokenEndpointMutationResult = NonNullable<Awaited<ReturnType<typeof acquireTokenEndpoint>>>
    export type AcquireTokenEndpointMutationBody = GalleraiApplicationFeaturesAuthAcquireTokenRequest
    export type AcquireTokenEndpointMutationError = ErrorType<unknown>

    export const useAcquireTokenEndpoint = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acquireTokenEndpoint>>, TError,{data: GalleraiApplicationFeaturesAuthAcquireTokenRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof acquireTokenEndpoint>>,
        TError,
        {data: GalleraiApplicationFeaturesAuthAcquireTokenRequest},
        TContext
      > => {
      return useMutation(getAcquireTokenEndpointMutationOptions(options));
    }
    
