// <auto-generated />
using System;
using Gallerai.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gallerai.Infrastructure.Migrations
{
    [DbContext(typeof(GalleraiDbContext))]
    partial class GalleraiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gallerai.Domain.Entities.ImageEntities.Image", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("R2Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("ImageId");

                    b.HasIndex("R2Key")
                        .IsUnique();

                    b.HasIndex("UploadedAt");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Gallerai.Domain.Entities.ImageEntities.ImageAnalysis", b =>
                {
                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<double>("AestheticScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Critique")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("ImageId");

                    b.ToTable("ImageAnalyses");
                });

            modelBuilder.Entity("Gallerai.Domain.Entities.ImageEntities.ImageEvent", b =>
                {
                    b.Property<Guid>("ImageEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ImageEventId");

                    b.HasIndex("ImageId", "LastUpdate");

                    b.ToTable("ImageEvents");
                });

            modelBuilder.Entity("Gallerai.Domain.Entities.ImageEntities.ImageMetadata", b =>
                {
                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ImageId");

                    b.ToTable("ImageMetadata");
                });

            modelBuilder.Entity("Gallerai.Domain.Entities.ImageEntities.ImageState", b =>
                {
                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ImageId");

                    b.HasIndex("Status");

                    b.ToTable("ImageStates");
                });

            modelBuilder.Entity("Gallerai.Domain.Entities.ImageEntities.ImageTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.ToTable("ImageTags");
                });

            modelBuilder.Entity("ImageImageTag", b =>
                {
                    b.Property<Guid>("ImageListImageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImageTagsId")
                        .HasColumnType("uuid");

                    b.HasKey("ImageListImageId", "ImageTagsId");

                    b.HasIndex("ImageTagsId");

                    b.ToTable("ImageImageTag");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("Gallerai.Domain.Entities.ImageEntities.ImageAnalysis", b =>
                {
                    b.HasOne("Gallerai.Domain.Entities.ImageEntities.Image", "Image")
                        .WithOne("Analysis")
                        .HasForeignKey("Gallerai.Domain.Entities.ImageEntities.ImageAnalysis", "ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Gallerai.Domain.Entities.ImageEntities.ImageEvent", b =>
                {
                    b.HasOne("Gallerai.Domain.Entities.ImageEntities.Image", "Image")
                        .WithMany("ImageEvents")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Gallerai.Domain.Entities.ImageEntities.ImageMetadata", b =>
                {
                    b.HasOne("Gallerai.Domain.Entities.ImageEntities.Image", "Image")
                        .WithOne("Metadata")
                        .HasForeignKey("Gallerai.Domain.Entities.ImageEntities.ImageMetadata", "ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Gallerai.Domain.Entities.ImageEntities.CameraInfo", "Camera", b1 =>
                        {
                            b1.Property<Guid>("ImageMetadataImageId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CapturedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LensModel")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("Make")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("Model")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("Software")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.HasKey("ImageMetadataImageId");

                            b1.ToTable("ImageMetadata");

                            b1.WithOwner()
                                .HasForeignKey("ImageMetadataImageId");
                        });

                    b.OwnsOne("Gallerai.Domain.Entities.ImageEntities.ExposureSettings", "Exposure", b1 =>
                        {
                            b1.Property<Guid>("ImageMetadataImageId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("Aperture")
                                .HasColumnType("double precision");

                            b1.Property<double?>("ExposureCompensation")
                                .HasColumnType("double precision");

                            b1.Property<int>("Flash")
                                .HasColumnType("integer");

                            b1.Property<double?>("FocalLengthMm")
                                .HasColumnType("double precision");

                            b1.Property<int?>("Iso")
                                .HasColumnType("integer");

                            b1.Property<double?>("ShutterSpeedSeconds")
                                .HasColumnType("double precision");

                            b1.Property<int>("WhiteBalance")
                                .HasColumnType("integer");

                            b1.HasKey("ImageMetadataImageId");

                            b1.ToTable("ImageMetadata");

                            b1.WithOwner()
                                .HasForeignKey("ImageMetadataImageId");
                        });

                    b.Navigation("Camera");

                    b.Navigation("Exposure");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Gallerai.Domain.Entities.ImageEntities.ImageState", b =>
                {
                    b.HasOne("Gallerai.Domain.Entities.ImageEntities.Image", "Image")
                        .WithOne("Status")
                        .HasForeignKey("Gallerai.Domain.Entities.ImageEntities.ImageState", "ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("ImageImageTag", b =>
                {
                    b.HasOne("Gallerai.Domain.Entities.ImageEntities.Image", null)
                        .WithMany()
                        .HasForeignKey("ImageListImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gallerai.Domain.Entities.ImageEntities.ImageTag", null)
                        .WithMany()
                        .HasForeignKey("ImageTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("Gallerai.Domain.Entities.ImageEntities.Image", b =>
                {
                    b.Navigation("Analysis")
                        .IsRequired();

                    b.Navigation("ImageEvents");

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
