using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Gallerai.SourceGenerators;

[Generator]
public class SettingsRegistrationGenerator : IIncrementalGenerator
{
    private const string SettingsScopeAttributeName = "Gallerai.SharedKernel.Attributes.SettingsScopeAttribute";
    private const string SharedScope = "Shared";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var settingsClasses = context.CompilationProvider.Select((compilation, token) =>
        {
            var markerSymbol = compilation.GetTypeByMetadataName("Gallerai.SharedKernel.IAssemblyMarker");
            var iSettingsSymbol = compilation.GetTypeByMetadataName("Gallerai.SharedKernel.Interfaces.ISettings");
            var scopeAttributeSymbol = compilation.GetTypeByMetadataName(SettingsScopeAttributeName);

            if (markerSymbol == null || iSettingsSymbol == null)
                return (ImmutableArray<string>.Empty, string.Empty);

            var targetAssembly = markerSymbol.ContainingAssembly;
            var consumingAssemblyName = compilation.AssemblyName ?? string.Empty;

            var foundClasses = ImmutableArray.CreateBuilder<string>();
            ScanNamespace(targetAssembly.GlobalNamespace, iSettingsSymbol, scopeAttributeSymbol, consumingAssemblyName, foundClasses);

            return (foundClasses.ToImmutable(), consumingAssemblyName);
        });

        context.RegisterSourceOutput(settingsClasses, (spc, result) =>
        {
            var (classes, targetNamespace) = result;
            if (classes.IsDefaultOrEmpty) return;

            var code = GenerateCode(classes, targetNamespace);
            spc.AddSource("GeneratedSettingsExtensions.g.cs", SourceText.From(code, Encoding.UTF8));
        });
    }

    private void ScanNamespace(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol interfaceSymbol,
        INamedTypeSymbol? scopeAttributeSymbol,
        string consumingAssemblyName,
        ImmutableArray<string>.Builder results)
    {
        foreach (var member in namespaceSymbol.GetMembers())
        {
            if (member is INamespaceSymbol subNamespace)
            {
                ScanNamespace(subNamespace, interfaceSymbol, scopeAttributeSymbol, consumingAssemblyName, results);
            }
            else if (member is INamedTypeSymbol typeSymbol)
            {
                if (typeSymbol.TypeKind == TypeKind.Class && !typeSymbol.IsAbstract &&
                    typeSymbol.AllInterfaces.Contains(interfaceSymbol, SymbolEqualityComparer.Default))
                {
                    if (IsSettingInScope(typeSymbol, scopeAttributeSymbol, consumingAssemblyName))
                    {
                        results.Add(typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                    }
                }
            }
        }
    }

    private bool IsSettingInScope(
        INamedTypeSymbol typeSymbol,
        INamedTypeSymbol? scopeAttributeSymbol,
        string consumingAssemblyName)
    {
        if (scopeAttributeSymbol == null)
            return true; // No scoping, include all

        var scopeAttributes = typeSymbol.GetAttributes()
            .Where(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, scopeAttributeSymbol))
            .ToList();

        // No scope attribute means include in all projects
        if (!scopeAttributes.Any())
            return true;

        // Check if any scope matches the consuming assembly or is "Shared"
        return scopeAttributes.Any(attr =>
        {
            var scopeValue = attr.ConstructorArguments.FirstOrDefault().Value?.ToString();
            return scopeValue == SharedScope || scopeValue == consumingAssemblyName;
        });
    }

    private string GenerateCode(ImmutableArray<string> classNames, string targetNamespace)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine("using Microsoft.Extensions.Options;");

        sb.AppendLine($"namespace {targetNamespace};");

        sb.AppendLine("public static class GeneratedSettingsExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddGeneratedSettings(this IServiceCollection services, IConfiguration configuration)");
        sb.AppendLine("    {");

        foreach (var className in classNames)
        {
            sb.AppendLine($@"        services.AddOptions<{className}>()
            .Bind(configuration.GetSection({className}.SectionName))
            .ValidateDataAnnotations()
            .ValidateOnStart();");

            sb.AppendLine($@"        services.AddSingleton(sp => 
            sp.GetRequiredService<IOptions<{className}>>().Value);");
            sb.AppendLine();
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
